### PR TITLE
fix: request_headers

### PR DESCRIPTION
**Pull request by t-umeno**
fix: request_headers

change from '"Authorization" : authorization' to '"Authorization" : authorization'

### CODE REVIEW

**Comment by kyle-winters** [comment]
@johnheintz do you know if the auth header format changed?

**Comment by kyle-winters** [comment]
> fix: request_headers
> 
> change from '"Authorization" : authorization' to '"Authorization" : authorization'

@t-umeno it was just the extra space inside the string?

**Review by johnheintz — APPROVED** [review]

**Comment by johnheintz** [comment]
Thanks @t-umeno

**Comment by t-umeno** [comment]
Thanks!

2020年8月4日(火) 6:39 John Heintz <notifications@github.com>:

**Pull request merged**
